name: 'Get Semver Info'
description: 'Get Semantic version information from git repo'
author: 'vkotha'

inputs:
  github_token:
    description: 'Github token'
    required: true
  release_branches:
    description: 'Release branches'
    required: false
    default: 'main,^(releases\/)?[0-9]+\.[0-9]+\.x$'

outputs:
  next_tag:
    description: 'Next Semantic tag'
    value: ${{ steps.release_version.outputs.next_tag }}
  next_version:
    description:  'Next Semantic version'
    value: ${{ steps.release_version.outputs.next_version }}
  previous_tag:
    description: 'Previous tag'
    value: ${{steps.release_version.outputs.previous_tag }}
  previous_version:
    description:  'Previous Semantic version'
    value: ${{ steps.release_version.outputs.previous_version }}
  version:
    description: 'Suggested release version'
    value: ${{steps.release_version.outputs.version }}
  part:
    description: 'The part of version which was bumped'
    value: ${{steps.release_version.outputs.part }}

runs:
  using: 'composite'
  steps:
    - name: Version check
      id: bump
      uses: vkkotha/github-tag-action@1.37.0-beta.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        WITH_V: true
        RELEASE_BRANCHES: ${{ inputs.release_branches }}
        DRY_RUN: true
        TAG_CONTEXT: branch
        BUMP_STRATEGY: angular
        DEFAULT_BUMP: minor
        VERBOSE: true
    - name: Get version
      id: release_version
      run: |
        if [[ "$GITHUB_REF" =~ ^refs/heads/.* ]]; then echo "::set-output name=version::${NEW_TAG:1}-SNAPSHOT"; fi
        if [[ "$GITHUB_REF" =~ ^refs/tags/v.* ]]; then echo "::set-output name=version::${TAG:1}-SNAPSHOT"; fi
        echo "::set-output name=next_tag::${NEW_TAG}"
        echo "::set-output name=next_version::${NEW_TAG:1}"
        echo "::set-output name=previous_tag::${TAG}"
        echo "::set-output name=previous_version::${TAG:1}"
        echo "::set-output name=part::${PART}"
      env:
        NEW_TAG: ${{ steps.bump.outputs.new_tag }}
        TAG: ${{ steps.bump.outputs.tag }}
        PART: ${{ steps.bump.outputs.part }}
