name: 'Get Semver Info'
description: 'Get Semantic version information from git repo'
author: 'vkotha'

inputs:
  github_token:
    description: 'Github token'
    required: true
  release_branches:
    description: 'Release branches'
    required: false
    default: 'main,^(releases\/)?[0-9]+\.[0-9]+\.x$'

outputs:
  next_tag:
    description: 'Next Semantic tag'
    value: ${{ steps.release_version.outputs.next_tag }}
  next_version:
    description:  'Next Semantic version'
    value: ${{ steps.release_version.outputs.next_version }}
  previous_tag:
    description: 'Previous tag'
    value: ${{steps.release_version.outputs.previous_tag }}
  previous_version:
    description:  'Previous Semantic version'
    value: ${{ steps.release_version.outputs.previous_version }}
  version:
    description: 'Suggested release version'
    value: ${{steps.release_version.outputs.version }}
  part:
    description: 'The part of version which was bumped'
    value: ${{steps.release_version.outputs.part }}

runs:
  using: 'composite'
  steps:
    - name: Version check
      id: bump_main
      uses: vkkotha/github-tag-action@1.37.0-beta.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        WITH_V: true
        RELEASE_BRANCHES: ${{ inputs.release_branches }}
        DRY_RUN: true
        TAG_CONTEXT: branch
        BUMP_STRATEGY: angular
        DEFAULT_BUMP: patch
        VERBOSE: false
    - name: Version check
      id: bump_branch
      uses: vkkotha/github-tag-action@1.37.0-beta.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        WITH_V: true
        RELEASE_BRANCHES: ${{ inputs.release_branches }}
        DRY_RUN: true
        TAG_CONTEXT: branch
        BUMP_STRATEGY: skip
        DEFAULT_BUMP: patch
        VERBOSE: false
    - name: Get version
      id: release_version
      shell: bash
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "Version Info: new_tag: ${{ steps.bump.outputs.new_tag }}, tag: ${{ steps.bump.outputs.tag }}"
        if [[ "$GITHUB_REF" == refs/heads/main ]]; then
          echo "::set-output name=version::${MAIN_TAG:1}-SNAPSHOT";
          echo "::set-output name=next_tag::${MAIN_TAG}"
          echo "::set-output name=next_version::${MAIN_TAG:1}"
        elif [[ "$GITHUB_REF" =~ ^refs/heads/.* ]]; then
          echo "::set-output name=version::${BRANCH_TAG:1}-SNAPSHOT";
          echo "::set-output name=next_tag::${BRANCH_TAG}"
          echo "::set-output name=next_version::${BRANCH_TAG:1}"
        else
          echo "::set-output name=version::${TAG:1}";
        fi
        echo "::set-output name=previous_tag::${TAG}"
        echo "::set-output name=previous_version::${TAG:1}"
      env:
        MAIN_TAG: ${{ steps.bump_main.outputs.new_tag }}
        BRANCH_TAG: ${{ steps.bump_branch.outputs.new_tag }}
        TAG: ${{ steps.bump_main.outputs.tag }}
